
GET http://localhost:8000/api/v1/auth/user/profile
Authorization: Bearer 

###
POST http://localhost:8000/api/v1/auth/signin
Content-Type: "application/json"

{
    "userSignIn": "khanhly123",
    "password": "123456789"
}